### ISSUE TITLE
Suggestion: Design for page references

### ISSUE THREAD

**Issue by eryc-cc** [gavinmn/logseq-luma#19]
## Summary:

Suggestion to make the Page References look cooler, without the brackets, and more like a pill/card with a `P` inside, indicating that it's a page:

<img width="141" alt="Screen Shot 2022-07-29 at 7 29 17 PM" src="https://user-images.githubusercontent.com/101464991/181853576-32e3b0b0-dfd0-4332-ab58-34f7aac9748d.png">

The brackets still show when you're editing the text. They just won't show on the rendered blocks.

<img width="181" alt="Screen Shot 2022-07-29 at 7 30 28 PM" src="https://user-images.githubusercontent.com/101464991/181853658-d9a8df89-a3a7-4050-abab-a74337bf7870.png">

### CSS:

```css
.page-ref {
  display: inline-flex;
  align-items: center;

  font-size: 0.875rem;
  font-weight: 600;
  letter-spacing: -0.03em;
  line-height: 1;

  padding: .125rem .375rem;
  padding-left: .25rem;

  border: 1px solid var(--color-level-2);
  border-radius: .375rem;
  background-color: var(--color-level-1);
}
.page-ref:hover {
  border-color: var(--color-level-3);
  background-color: var(--color-level-2);
}

.page-ref:before {
  content: "P";
  
  font-size: .875em;
  font-weight: 600;
  line-height: 1;
  
  padding: .125rem .25rem;
  margin-right: 0.25rem;

  color: slategray;
  border: 1px solid var(--color-level-3);
  border-radius: .25rem;
  background: var(--color-level-2);
  
  transition: all 260ms ease;
}
.page-ref:hover:before {
  border-color: var(--color-level-4);
  background-color: var(--color-level-3);
}

.page-reference .bracket {
  display: none;
}
```
