### ISSUE TITLE
Update contrast of checkboxes in All Pages (light mode)

### ISSUE THREAD

**Issue by martindufort** [gavinmn/logseq-luma#39]
The contrast of the checkbox in the All Pages view (in light mode) is very difficult to see especially for the gray row.

<img width="318" alt="CleanShot 2022-08-09 at 19 05 23" src="https://user-images.githubusercontent.com/28934641/183776862-30b8235c-dfae-45c5-9da8-428744ae70cc.png">

**Comment by patrick91** [comment]
If someone wants a quick workaround for this:

```css
html[data-theme=light] .form-checkbox:checked {
  background-color: #10ab47;
}
```
